### PR TITLE
improved code quality + sbt upgrade

### PR DESCRIPTION
**Pull request by matiwinnetou**

### CODE REVIEW

**Comment by Happy0** [comment]
Haha, that was unexpected! Thanks very much :D.

Are you planning to do something with the library, or did you do the refactoring as a learning exercise?

I will accept the pull request soon after I've had a closer look.

**Comment by matiwinnetou** [comment]
It is both, but I am considering improving this, providing some server engine and ability for people to play maybe. I know the library is GPL'ed so the fork will stay GPL'ed as well.

**Comment by Happy0** [comment]
That's great to hear! I look forward to seeing your progress if you push your changes to github.

Are you planning to build a separate application, using scalascrabble (with your modifications) as a library, or to modify the scalascrabble project into a server?

I'm currently trying to build a web app on top of https://github.com/happy0/haskellscrabble, but it's tough to get started =p.

**Comment by matiwinnetou** [comment]
I don't know yet. exploring and playing around at the moment.

BTW: great work as for a Scala beginner. Don't push blame yourself, you did awesome work.

**Comment by Happy0** [comment]
Thanks a lot :D.

**Pull request merged**
